### ISSUE TITLE
About byt5-small

### ISSUE THREAD

**Issue by luyi98** [lingjzhu/CharsiuG2P#10]
I try to run model charsiu/g2p_multilingual_byT5_small using huggingface in france g2p, but it always raises an error "OSError: Can't load tokenizer for 'charsiu/g2p_multilingual_byT5_small_100'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'charsiu/g2p_multilingual_byT5_small_100' is the correct path to a directory containing all relevant files for a ByT5Tokenizer tokenizer." This is true both in the Hosted inference API and locally using the transformers library.

**Comment by lingjzhu** [comment]
You actually don't need a tokenizer for byte-level models as you can directly convert strings to UTF8 encodings and use them as input to the model.  Or you can simply use the following tokenizer: 
tokenizer = AutoTokenizer.from_pretrained('google/byt5-small')

You can check out [this example](https://huggingface.co/docs/transformers/model_doc/byt5#example) about tokenizing strings into byte-level encoding

**Comment by luyi98** [comment]
Thanks! I successfully ran the code with the tokenizer you gave me. But I still have a question to ask, can the French phonemes generated by byt5-small include Liaisons?

**Comment by lingjzhu** [comment]
I don't think so. In our training data, Liaisons are not marked. So I don't think the G2P models can predict that.

**Comment by luyi98** [comment]
Ok, thank you very much！
