### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by The0nix** [lingjzhu/CharsiuG2P#8]
Hello. In the README you write:
> Pretrained models are hosted at [HuggingFace model hub](https://huggingface.co/charsiu) with the prefix "G2P". We are still in the process of uploading models.

I don't see any G2P models there. When will you upload your models?

**Comment by lingjzhu** [comment]
Thank you for your interest. I finally had time to upload models this week. I will also write a simple tutorial soon. You should see some of them now. They can be loaded using the standard huggingface interface. More pretrained models will be coming soon.
